trending_product:
  description: >
    Find a list of 2 trending categories on daraz.pk website. Then find the top 2 trending products of the category found and their price.
  expected_output: >
    A string representing a trending list of category and their top 2 products with price on daraz.pk from the category.
  agent: researcher


