find_category:
  description: >
    Find a top 3 trending category on Daraz.
  expected_output: >
    Return a string representing a list of 3 trending category on Daraz.
  agent: researcher


trending_product:
  description: >
    Find a top 5 trending product from the category found through by find_category.
  expected_output: >
    A string representing a trending list of 5 products on Daraz from the category found through find_category.
  agent: researcher

trending_product_price:
  description: >
    Find the price of the trending product found through by trending_product.
  expected_output: >
    A string representing the price of the trending product found through by trending_product.
  agent: researcher


